/*  Machine generated symbol file "esentprf.hxx" from "perfdata.txt" */


#define ESE 0
#define PagesConvertedSec 2
#define PagesConvertedTotal 4
#define RecordsConvertedSec 6
#define RecordsConvertedTotal 8
#define OSHeapAllocPerSec 10
#define OSHeapFreePerSec 12
#define OSHeapAlloc 14
#define OSHeapBytesAlloc 16
#define OSPageBytesReserved 18
#define OSPageBytesCommitted 20
#define FCBAsyncScan 22
#define FCBAsyncPurge 24
#define FCBAsyncThresholdScan 26
#define FCBAsyncThresholdPurge 28
#define FCBAsyncPurgeConflict 30
#define FCBSyncPurge 32
#define FCBSyncPurgeStalls 34
#define FCBCacheHits 36
#define FCBCacheRequests 38
#define FCBCacheStalls 40
#define FCBCacheMax 42
#define FCBCachePreferred 44
#define FCBCacheAlloc 46
#define FCBCacheAllocAvail 48
#define PIBInUse 50
#define PIBUsed 52
#define PIBTotal 54
#define TableOpenCacheHitRate 56
#define TableOpenCacheRequests 58
#define TableOpenCacheHitsPerSec 60
#define TableOpenCacheMissesPerSec 62
#define TableOpensPerSec 64
#define LGBytesWrittenPerSec 66
#define LGUsersWaiting 68
#define UserROTrxCommit0PerSec 70
#define UserRWTrxCommit0PerSec 72
#define UserTrxCommit0PerSec 74
#define UserROTrxRollback0PerSec 76
#define UserRWTrxRollback0PerSec 78
#define UserTrxRollback0PerSec 80
#define SystemROTrxCommit0PerSec 82
#define SystemRWTrxCommit0PerSec 84
#define SystemTrxCommit0PerSec 86
#define SystemROTrxRollback0PerSec 88
#define SystemRWTrxRollback0PerSec 90
#define SystemTrxRollback0PerSec 92
#define IODatabaseFileExtensionStall 94
#define LGRecordPerSec 96
#define LGCapacityFlushPerSec 98
#define LGCommitFlushPerSec 100
#define LGFlushPerSec 102
#define LGWritePerSec 104
#define LGStallPerSec 106
#define VERcbucketAllocated 108
#define VERcbucketDeleteAllocated 110
#define VERcbAverageBookmark 112
#define VERUnnecessaryCalls 114
#define BTAppendSplit 116
#define BTRightSplit 118
#define BTVerticalSplit 120
#define BTSplit 122
#define BTEmptyPageMerge 124
#define BTRightMerge 126
#define BTPartialMerge 128
#define BTMerge 130
#define BTSeekShortCircuit 132
#define BTUnnecessarySiblingLatch 134
#define BTNext 136
#define BTPrev 138
#define BTSeek 140
#define BTInsert 142
#define BTReplace 144
#define BTFlagDelete 146
#define BTDelete 148
#define BTAppend 150
#define SPCreate 152
#define SPCreateCum 154
#define SPDelete 156
#define SPDeleteCum 158
#define BFCacheHits 160
#define BFCacheRequests 162
#define BFPctClean 164
#define BFTotalBuffers2 166
#define BFPagesReadPerSec 168
#define BFPagesWrittenPerSec 170
#define BFPagesTransferredPerSec 172
#define BFLatch 174
#define BFFastLatch 176
#define BFBadLatchHint 178
#define BFPctFastLatch 180
#define BFTotalLatches 182
#define BFLatchConflict 184
#define BFLatchStall 186
#define BFPctAvail 188
#define BFTotalBuffers3 190
#define BFCacheFault 192
#define BFCacheEvict 194
#define BFAvailStallsPerSec 196
#define BFCacheSize 198
#define BFPctStartFlushThreshold 200
#define BFTotalBuffers4 202
#define BFPctStopFlushThreshold 204
#define BFTotalBuffers5 206
#define BFPagesPreread 208
#define BFCachedPagesPreread 210
#define BFPagesPrereadUntouched 212
#define BFPagesVersioned 214
#define BFPctVersioned 216
#define BFTotalBuffers6 218
#define BFPagesOrdinarilyWritten 220
#define BFPagesAnomalouslyWritten 222
#define BFPagesOpportunelyWritten 224
#define BFPagesRepeatedlyWritten 226
#define BFPagesIdlyWritten 228
#define BFPageHistory 230
#define BFPageHistoryHits 232
#define BFPageHistoryReqs 234
#define BFPageScanned 236
#define BFPageScannedOutOfOrder 238
#define BFPageScannedTotal 240
#define OLDSLVChunkSize 242
#define OSSLVFileTableInserts 244
#define OSSLVFileTableCleans 246
#define OSSLVFileTableDeletes 248
#define OSSLVFileTableEntries 250
#define OSSYNCThreadBlock 252
#define OSSYNCThreadsBlocked 254
#define Instances 256
#define IPagesConvertedSec 258
#define IPagesConvertedTotal 260
#define IRecordsConvertedSec 262
#define IRecordsConvertedTotal 264
#define IFCBAsyncScan 266
#define IFCBAsyncPurge 268
#define IFCBAsyncThresholdScan 270
#define IFCBAsyncThresholdPurge 272
#define IFCBAsyncPurgeConflict 274
#define IFCBSyncPurge 276
#define IFCBSyncPurgeStalls 278
#define IFCBCacheHits 280
#define IFCBCacheRequests 282
#define IFCBCacheStalls 284
#define IFCBCacheMax 286
#define IFCBCachePreferred 288
#define IFCBCacheAlloc 290
#define IFCBCacheAllocAvail 292
#define IPIBInUse 294
#define IPIBUsed 296
#define IPIBTotal 298
#define ITableOpenCacheHitRate 300
#define ITableOpenCacheRequests 302
#define ITableOpenCacheHitsPerSec 304
#define ITableOpenCacheMissesPerSec 306
#define ITableOpensPerSec 308
#define ILGBytesWrittenPerSec 310
#define ILGUsersWaiting 312
#define ILGCheckpointDepth 314
#define IUserROTrxCommit0PerSec 316
#define IUserRWTrxCommit0PerSec 318
#define IUserTrxCommit0PerSec 320
#define IUserROTrxRollback0PerSec 322
#define IUserRWTrxRollback0PerSec 324
#define IUserTrxRollback0PerSec 326
#define ISystemROTrxCommit0PerSec 328
#define ISystemRWTrxCommit0PerSec 330
#define ISystemTrxCommit0PerSec 332
#define ISystemROTrxRollback0PerSec 334
#define ISystemRWTrxRollback0PerSec 336
#define ISystemTrxRollback0PerSec 338
#define IIODatabaseFileExtensionStall 340
#define ILGRecordPerSec 342
#define ILGCapacityFlushPerSec 344
#define ILGCommitFlushPerSec 346
#define ILGFlushPerSec 348
#define ILGWritePerSec 350
#define ILGStallPerSec 352
#define IVERcbucketAllocated 354
#define IVERcbucketDeleteAllocated 356
#define IVERcrceHashUsage 358
#define IVERcbAverageBookmark 360
#define IVERUnnecessaryCalls 362
#define IBTAppendSplit 364
#define IBTRightSplit 366
#define IBTVerticalSplit 368
#define IBTSplit 370
#define IBTEmptyPageMerge 372
#define IBTRightMerge 374
#define IBTPartialMerge 376
#define IBTMerge 378
#define IBTSeekShortCircuit 380
#define IBTUnnecessarySiblingLatch 382
#define IBTNext 384
#define IBTPrev 386
#define IBTSeek 388
#define IBTInsert 390
#define IBTReplace 392
#define IBTFlagDelete 394
#define IBTDelete 396
#define IBTAppend 398
#define ISPCreate 400
#define ISPCreateCum 402
#define ISPDelete 404
#define ISPDeleteCum 406
#define IBFPagesReadPerSec 408
#define IBFPagesWrittenPerSec 410
#define IBFPagesTransferredPerSec 412
#define IBFPagesPreread 414
#define IBFCachedPagesPreread 416
#define IBFPagesPrereadUntouched 418
#define IBFPagesVersioned 420
#define IBFPagesOrdinarilyWritten 422
#define IBFPagesAnomalouslyWritten 424
#define IBFPagesOpportunelyWritten 426
#define IBFPagesRepeatedlyWritten 428
#define IBFPagesIdlyWritten 430
