[info]

drivername=RSVP
symbolfile=rsvpcnts.h

[objects]
RSVP_009_NAME=RSVP service

[languages]
009=English

[text]
RSVPOBJ_009_NAME=RSVP Service
RSVPOBJ_009_HELP=RSVP service performance counters.

RSVP_INTERFACES_009_NAME=Network Interfaces
RSVP_INTERFACES_009_HELP=The number of local network interfaces visible to, and used by the RSVP service.

RSVP_NET_SOCKETS_009_NAME=Network sockets
RSVP_NET_SOCKETS_009_HELP=The total number of raw sockets opened for the purpose of RSVP signaling. 

RSVP_TIMERS_009_NAME=Timers
RSVP_TIMERS_009_HELP=The number of timer events scheduled to take place. Shows the activity level of the RSVP service.

API_SESSIONS_009_NAME=RSVP sessions
API_SESSIONS_009_HELP=The current number of active RSVP sessions on the RSVP service.

API_CLIENTS_009_NAME=QoS clients
API_CLIENTS_009_HELP=The number of QoS enabled applications currently active.

API_PATH_009_NAME=QoS-enabled senders
API_PATH_009_HELP=Indicates the number of PATH messages sent for QoS-enabled senders. This number increments each time a PATH is refreshed.

API_RESV_009_NAME=QoS-enabled receivers
API_RESV_009_HELP=Indicates the number of RESV messages sent for QoS-enabled receivers. This number increments each time a RESV is refreshed.

API_FAILED_REQ_009_NAME=Failed QoS requests
API_FAILED_REQ_009_HELP=The number of QoS requests generated by QoS-enabled applications that have been rejected by the RSVP service. Failed QoS requests can be caused by invalid QoS requests. 

API_FAILED_SEND_009_NAME=Failed QoS sends
API_FAILED_SEND_009_HELP=The number of QoS notifications the RSVP service that could not be sent to the QoS applications. Failed QoS sends can be caused by terminated applications.

API_QOS_NOTIFIES_009_NAME=QoS notifications
API_QOS_NOTIFIES_009_HELP=The number of QoS notifications delivered to QoS-enabled applications by the QoS RSVP service.

API_QOS_NOTIF_BYTES_009_NAME=Bytes in QoS notifications
API_QOS_NOTIF_BYTES_009_HELP=A running total of the number of bytes delivered in QoS Notifications to QoS-enabled applications.

RSVPIFOBJ_009_NAME=RSVP Interfaces
RSVPIFOBJ_009_HELP=RSVP Interfaces performance counters.

TOTAL_BYTES_IN_009_NAME=Signaling bytes received
TOTAL_BYTES_IN_009_HELP=Total RSVP signaling traffic in bytes received by the RSVP service on this interface.

TOTAL_BYTES_OUT_009_NAME=Signaling bytes sent
TOTAL_BYTES_OUT_009_HELP=Total RSVP signaling traffic in bytes sent by the RSVP service on this interface.

PATH_MSG_IN_009_NAME=PATH messages received
PATH_MSG_IN_009_HELP=The total number of PATH messages received on this interface.

RESV_MSG_IN_009_NAME=RESV messages received
RESV_MSG_IN_009_HELP=The total number of RESV messages received on this interface.

PATH_ERR_MSG_IN_009_NAME=PATH ERR messages received
PATH_ERR_MSG_IN_009_HELP=The total number of PATH error messages received on this interface. This number indicates the number of times a PATH has been rejected by a remote host. 

RESV_ERR_MSG_IN_009_NAME=RESV ERR messages received
RESV_ERR_MSG_IN_009_HELP=The total number of RESV ERR messages received on this interface by the RSVP service rejecting incoming RESV messages.

PATH_TEAR_MSG_IN_009_NAME=PATH TEAR messages received
PATH_TEAR_MSG_IN_009_HELP=The total number of PATH TEAR messages received on the interface. 

RESV_TEAR_MSG_IN_009_NAME=RESV TEAR messages received
RESV_TEAR_MSG_IN_009_HELP=The total number of RESV TEAR messages received on the interface.

CONFIRM_MSG_IN_009_NAME=RESV CONFIRM messages received
CONFIRM_MSG_IN_009_HELP=The total number of RESV CONFIRM messages received by the interface.

PATH_MSG_OUT_009_NAME=PATH messages sent
PATH_MSG_OUT_009_HELP=The total number of PATH messages sent by the RSVP service sent on this the interface.

RESV_MSG_OUT_009_NAME=RESV messages sent
RESV_MSG_OUT_009_HELP=The total number of RESV messages sent by the RSVP service sent on this the interface

PATH_ERR_MSG_OUT_009_NAME=PATH ERR messages sent
PATH_ERR_MSG_OUT_009_HELP=The total number of PATH ERR messages sent by the RSVP service rejecting incoming PATH messages. 

RESV_ERR_MSG_OUT_009_NAME=RESV ERR messages sent
RESV_ERR_MSG_OUT_009_HELP=The total number of RESV error sent on this interface. This number indicates how many reservations have been rejected by the network. 

PATH_TEAR_MSG_OUT_009_NAME=PATH TEAR messages sent
PATH_TEAR_MSG_OUT_009_HELP=The total number of PATH TEAR messages sent on the interface to tear down an RSVP PATH state in the network.

RESV_TEAR_MSG_OUT_009_NAME=RESV TEAR messages sent
RESV_TEAR_MSG_OUT_009_HELP=The total number of RESV TEAR messages sent on the interface to tear down a RESV state in the network.

CONFIRM_MSG_OUT_009_NAME=RESV CONFIRM messages sent
CONFIRM_MSG_OUT_009_HELP=The total number of RESV CONFIRM messages sent on this interface in response to RESV messages sent from remote hosts.

ADMISS_FAILS_009_NAME=Resource control failures
ADMISS_FAILS_009_HELP=This counter shows the number of reservations that failed due to the lack of resources. 

POLICY_FAILS_009_NAME=Policy control failures
POLICY_FAILS_009_HELP=This is the total number of RSVP requests that are not admitted on this interface due to a conflict with policy settings.

OTHER_FAILS_009_NAME=General failures
OTHER_FAILS_009_HELP=This is the total number of non-admission control errors that have occurred on this interface. For more information about the other traffic control failures, see RFC 2205.

BLOCKADE_EV_009_NAME=Blocked RESVs
BLOCKADE_EV_009_HELP=The number of blockaded reservations that failed due to failed reservations that have not been removed from this node. For more information about blockade states, see RFC 2205.

RESV_TIMEOUT_009_NAME=RESV state block timeouts
RESV_TIMEOUT_009_HELP=The total number of times the RSVP RESV state block (RSB) timed out. This happens when no RESV messages are received within the designated timeout period. This error message can be caused by a route change. 

PATH_TIMEOUT_009_NAME=PATH state block timeouts
PATH_TIMEOUT_009_HELP=The total number of times the RSVP PATH state block (PSB) timed out. This happens when no PATH messages are received within the designated timeout period. This error message can be caused by a route change. 

SND_FAILS_BIG_MSG_009_NAME=Send messages errors - Big messages
SND_FAILS_BIG_MSG_009_HELP=The total number of outgoing RSVP messages dropped because they were bigger than the max configured RSVP message size.

RCV_FAILS_BIG_MSG_009_NAME=Receive messages errors - Big messages
RCV_FAILS_BIG_MSG_009_HELP=The total number of incoming RSVP messages dropped because they were bigger than the max configured RSVP message size.

SND_FAILS_NO_MEM_009_NAME=Send messages errors - No memory
SND_FAILS_NO_MEM_009_HELP=The total number of outgoing RSVP messages dropped due to insufficient memory.

RCV_FAILS_NO_MEM_009_NAME=Receive messages errors - No memory
RCV_FAILS_NO_MEM_009_HELP=The total number of incoming RSVP messages dropped due to insufficient memory.

DROPPED_IN_MSGS_009_NAME=Number of incoming messages dropped
DROPPED_IN_MSGS_009_HELP=Number of incoming messages dropped due to badly constructed RSVP objects etc.

DROPPED_OUT_MSGS_009_NAME=Number of outgoing messages dropped
DROPPED_OUT_MSGS_009_HELP=Number of outgoing messages dropped

ACTIVE_FLOWS_009_NAME=Number of active flows 
ACTIVE_FLOWS_009_HELP=The number of reserved flows currently installed and maintained by RSVP on this interface.

ALLOCATED_BW_009_NAME=Reserved bandwidth
ALLOCATED_BW_009_HELP=Shows the reserved bandwidth for this interface, in bits per second.

MAX_ALLOCATED_BW_009_NAME=Maximum admitted bandwidth
MAX_ALLOCATED_BW_009_HELP=The highest amount of allocated bandwidth admitted on the interface during the period in which the service has been running.

; Everything after this point should be deleted.
; 
; MSIDLPMOBJ_009_NAME=ACS Policy
; MSIDLPMOBJ_009_HELP=ACS policy based admission control counters.
; 
; SENDERS_ACCEPTED_009_NAME=PATH messages admitted
; SENDERS_ACCEPTED_009_HELP=The total number of PATH messages admitted by the ACS on this subnet.
; 
; SENDER_CHG_ACCEPTED_009_NAME=PATH message changes admitted
; SENDER_CHG_ACCEPTED_009_HELP=The total number of changes to PATH messages admitted by the ACS on this subnet.
; 
; REJ_SND_FLOW_RATE_009_NAME=Flow rate PATH rejections
; REJ_SND_FLOW_RATE_009_HELP=The total number of PATH messages rejected by the ACS due to the user per flow rate policy on this subnet.
; 
; REJ_SND_PEAK_RATE_009_NAME=Peak rate PATH rejections
; REJ_SND_PEAK_RATE_009_HELP=The total number of PATH messages rejected by the ACS due to the user per peak rate policy on this subnet.
; 
; REJ_SND_TFR_009_NAME=Total flow rate PATH rejections
; REJ_SND_TFR_009_HELP=The total number of PATH messages rejected by the ACS due to total flow rate policy on this subnet.
; 
; REJ_SND_TPR_009_NAME=Total peak rate PATH rejections
; REJ_SND_TPR_009_HELP=The total number of PATH messages rejected by the ACS due to total peak rate policy on this subnet.
; 
; REJ_SND_ID_CHG_009_NAME=User ID change PATH rejections
; REJ_SND_ID_CHG_009_HELP=The total number of PATH messages rejected by the ACS due to user ID change policy on this subnet.
; 
; REJ_SND_DURATION_009_NAME=Flow duration PATH rejections
; REJ_SND_DURATION_009_HELP=The total number of PATH messages rejected by the ACS due to flow duration policy on this subnet.
; 
; REJ_SND_FLOW_COUNT_009_NAME=Flow count PATH rejections
; REJ_SND_FLOW_COUNT_009_HELP=The total number of PATH messages rejected by the ACS due to flow count policy on this subnet.
; 
; REJ_SND_OTHERS_009_NAME=Other policy PATH rejections
; REJ_SND_OTHERS_009_HELP=The total number of PATH messages rejected by the ACS due to other policies on this subnet.
; 
; RECEIVERS_ACCEPTED_009_NAME=RESV messages admitted
; RECEIVERS_ACCEPTED_009_HELP=The total number of RESV messages admitted by the ACS on this subnet.
; 
; RECV_CHG_ACCEPTED_009_NAME=RESV message changes admitted
; RECV_CHG_ACCEPTED_009_HELP=Total number of changes to RESV messages admitted by the ACS on this subnet.
; 
; REJ_RECV_FLOW_RATE_009_NAME=Flow rate RESV rejections
; REJ_RECV_FLOW_RATE_009_HELP=The total number of RESV messages rejected by the ACS due to the user per flow rate policy on this subnet.
; 
; REJ_RECV_PEAK_RATE_009_NAME=Peak rate RESV rejections
; REJ_RECV_PEAK_RATE_009_HELP=The total number of RESV messages rejected by the ACS due to the user per peak rate policy on this subnet.
; 
; REJ_RECV_TFR_009_NAME=Total flow rate RESV rejections
; REJ_RECV_TFR_009_HELP=The total number of RESV messages rejected by the ACS due to total flow rate policy on this subnet.
; 
; REJ_RECV_TPR_009_NAME=Total peak rate RESV rejections
; REJ_RECV_TPR_009_HELP=The total number of RESV messages rejected by the ACS due to total peak rate policy on this subnet.
; 
; REJ_RECV_ID_CHG_009_NAME=User ID change RESV rejections
; REJ_RECV_ID_CHG_009_HELP=The total number of RESV messages rejected by the ACS due to user ID change policy on this subnet.
; 
; REJ_RECV_DURATION_009_NAME=Flow duration RESV rejections
; REJ_RECV_DURATION_009_HELP=The total number of RESV messages rejected by the ACS due to flow duration policy on this subnet.
; 
; REJ_RECV_FLOW_COUNT_009_NAME=Flow count RESV rejections
; REJ_RECV_FLOW_COUNT_009_HELP=The total number of RESV messages rejected by the ACS due to flow count policy on this subnet.
; 
; REJ_RECV_OTHERS_009_NAME=Other policy RESV rejections
; REJ_RECV_OTHERS_009_HELP=The total number of RESV messages rejected by the ACS due to other policies on this subnet.
; 
; BAD_IDENTITY_PES_009_NAME=Bad user Identity Policy Elements
; BAD_IDENTITY_PES_009_HELP=The total number of user identity policy elements which could not be identified by the Microsoft Identity LPM (MSIDLPM).
; 
; DS_CACHE_SIZE_009_NAME=DS cache size
; DS_CACHE_SIZE_009_HELP=Number of entries in the DS cache.


