// XPLogin10 - the files XPLogin10-Setup.exe carries inside itself.
//
// The whole product is embedded as RCDATA resources so the thing a user
// downloads is one file they double-click. payload.rc is generated by CMake
// from the real build outputs, so the setup can never ship a stale DLL.
#pragma once

#include <string>
#include <vector>

namespace xplogin::setup {

// Resource ids. Must match the generated payload.rc.
enum PayloadId {
    kPayloadProvider = 101,
    kPayloadWatchdog = 102,
    kPayloadInstall  = 103,
    // 104 was xplogin-preview.exe, a standalone host for looking at the screen
    // without signing out. Not part of the product; the id is left unused
    // rather than recycled so an old setup and a new one cannot disagree about
    // what a resource means.
    kPayloadConfig   = 105,
    kPayloadTheme    = 106,
    kPayloadAssets   = 107,  // XPLogin.assets, absent from a build with no artwork
    // XP's own sounds. Like the artwork, these are only embedded when the
    // reference material is present in assets/Media.
    kPayloadSoundLogon    = 108,
    kPayloadSoundLogoff   = 109,
    kPayloadSoundError    = 110,
    kPayloadSoundShutdown = 111,
};

// True when this binary was built with its payload embedded. A setup built
// without it still works when run from an unpacked build folder.
bool HasEmbeddedPayload();

// Writes every embedded file into `directory`, which is created if needed.
// Returns false and fills `error` if a required file could not be written.
bool ExtractAll(const std::wstring& directory, std::wstring* error);

// Files this setup can provide, whether embedded or sitting next to it.
const std::vector<std::wstring>& PayloadFileNames();

} // namespace xplogin::setup
